# Generated by Django 5.0.4 on 2024-05-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="body",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(null=True),
        ),
    ]
